# Generated by Django 5.2.7 on 2025-10-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dasboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('tipo_pared', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_sensores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
