# Generated by Django 5.2.7 on 2025-10-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dasboard', '0002_estadosensor_delete_sensordata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadosensor',
            table='estado_sensor',
        ),
    ]
